services:
    php:
        container_name: php${APP_CONTAINER_NAME}
        build:
            context: .
            dockerfile: 1.x.Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: ["sh", "-c", "php artisan lighthouse:cache && php artisan config:cache"]
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
        networks:
            - sail
    queue:
        container_name: queue
        build:
            context: .
            dockerfile: 1.x.Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: ["sh", "-c", "php artisan config:cache && php artisan queue:work --tries=3 --timeout=1750 --max-jobs=1000"]
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
        networks:
            - sail
    queue-social:
        container_name: queue-social
        build:
            context: .
            dockerfile: 1.x.Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: ["sh", "-c", "php artisan config:cache && php artisan queue:work --queue kanvas-social --tries=3 --timeout=1750 --max-jobs=1000"]
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
        networks:
            - sail
    queue-notifications:
        container_name: queue-notifications
        build:
            context: .
            dockerfile: 1.x.Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: ["sh", "-c", "php artisan config:cache && php artisan queue:work --queue notifications --tries=3 --timeout=1750 --max-jobs=1000"]
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
        networks:
            - sail
    nginx:
        image: nginx:latest
        container_name: nginx${APP_CONTAINER_NAME}
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - '.:/var/www/html'
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sail
        depends_on:
            - php
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            retries: 3
            timeout: 5s
    redis:
        container_name: redis${APP_CONTAINER_NAME}
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
