version: '3'
services:
    php:
        container_name: php${APP_CONTAINER_NAME}
        image: mctekk/kanvasapp:8.1-alpine
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-9000}:9000'
            - '${APP_PORT:-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - ../kanvas-core:/var/www/kanvas-core
            - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - sail
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:latest
        container_name: nginx${APP_CONTAINER_NAME}
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - '.:/var/www/html'
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sail
        depends_on:
            - php
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            retries: 3
            timeout: 5s
    mysql:
        container_name: mysql${APP_CONTAINER_NAME}
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    redis:
        container_name: redis${APP_CONTAINER_NAME}
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    rabbitmq:
        container_name: rabbitmq${APP_CONTAINER_NAME}
        image: rabbitmq:3.9.21-management-alpine
        hostname: "rabbit"
        env_file:
            - '.env'
        labels:
            NAME: "rabbitmq1"
        volumes:
            - "sail-rabbitmq:/var/lib/rabbitmq"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
          - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        restart: always
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
          - "9010:80"

        volumes:
          - pma:/var/www/html

        networks:
          - sail
networks:
    sail:
        driver: bridge
volumes:
    pma:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-rabbitmq:
        driver: local
