apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.deployments.queue.name}}
  namespace: {{.Values.namespace}}
spec:
  maxReplicas: 15
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.deployments.queue.name}}
  metrics:
    - type: Resource
      resource:
          name: cpu
          target:
              type: Utilization
              averageUtilization: 95
    - type: Resource
      resource:
          name: memory
          target:
              type: Utilization
              averageUtilization: 95
