apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanvas-api-ingress
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{.Values.staticIP.name}}
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: {{.Values.services.loadBalancer.name}}
      port:
        number: 80