apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployments.queue.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.deployments.queue.name}}
  template:
    metadata:
      labels:
        app: {{.Values.deployments.queue.name}}
        type: api
    spec:
      volumes:
        - name: envconfigmap
          configMap:
            name: envconfigmap
            items:
              - key: kanvasconfigmap
                path: .env
            defaultMode: 432
        - name: webroot
          emptyDir: {}
      containers:
        - name: {{.Values.deployments.api.containerName}}
          image: {{.Values.apiImage}}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: envconfigmap
              mountPath: /app/.env
              subPath: .env
            - name: webroot
              mountPath: "/var/www/html"
          resources:
                requests:
                    memory: "128M"
                    cpu: "100m"
                limits:
                    memory: "1G"
                    cpu: "500m"
          command:
            [
              "/bin/sh",
              "-c",
              "cp -R /app/. /var/www/html && \
               chmod -R 755 /var/www/html && \
               chmod -R 777 /var/www/html/storage && \
               chmod -R 777 /var/www/html/bootstrap/cache && \
               cd /var/www/html && \
               composer install && \
               php artisan queue:work"
            ]
      securityContext:
        fsGroup: 65533
