apiVersion: v1
kind: Service
metadata:
  name: graphapidev2
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: graphapidev2
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80