apiVersion: v1
kind: Service
metadata:
  name: graphapidev2
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: graphapidev2.kanvas.dev
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  selector:
    app: {{.Values.services.loadBalancer.appName}}
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80