apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: {{.Values.deployments.api.name}}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{.Values.deployments.api.name}}
  updatePolicy:
    updateMode: "Auto"