# General Values
# namespace:
# apiImage:

services:
  loadBalancer:
    name: graph
    appName: kanvas-cluster-api
    lbSSLCert: arn:aws:acm:us-east-1:617498580299:certificate/d26f7203-5607-4eee-ae5e-f9746c6fecae

# namespace: memod-api
apiImage: 617498580299.dkr.ecr.us-east-1.amazonaws.com/

# PHP INIT Values
php:
  memoryLimit: 2128M


# Deployments Values
deployments:
  api:
    name: kanvas-cluster-api
    containerName: api

# Services Values

