# General Values
# namespace:
# apiImage:

services:
  loadBalancer:
    name: graph
    appName: kanvas-cluster-api
    lbSSLCert: none

# namespace: memod-api
apiImage: 617498580299.dkr.ecr.us-east-1.amazonaws.com/

# PHP INIT Values
php:
  memoryLimit: 2128M


# Deployments Values
deployments:
  api:
    name: api
    containerName: api
  queue:
    name: queue
    containerName: queue

# Services Values

