name: SCP to Memod Elastic Indexer VM

on:
  workflow_dispatch:

jobs:
  scp-to-vm:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy folder content recursively to remote VM    
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USERNAME }}
        key: ${{ secrets.AWS_EC2_PRIVATE_SSH_KEY }}
        source: ${{ github.workspace }}
        target: ${{secrets.AWS_EC2_TARGET_DIR}}